### ISSUE TITLE
connection issues through telethon

### ISSUE THREAD

**Issue by getdzypher** [south1907/addmember-telegram#11]
File "init_session.py", line 1, in <module>
    from telethon import TelegramClient, connection
ImportError: cannot import name 'connection' from 'telethon'

**Comment by Rahul-Baba** [comment]
> File "init_session.py", line 1, in
> from telethon import TelegramClient, connection
> ImportError: cannot import name 'connection' from 'telethon'

Install telethon use this command - python -m pip install telethon

**Comment by abhisak74** [comment]
Use command pip -m install telethon
