### ISSUE TITLE
getdata.py Error

### ISSUE THREAD

**Issue by Rahul-Baba** [south1907/addmember-telegram#15]
Any one please help how to fix dang nhap khong thanh cong whan run getdata.py

**Comment by castipo** [comment]
The dev said this to me
![Screenshot_20200903-103840](https://user-images.githubusercontent.com/24226435/92068645-a88d4600-edd1-11ea-91bb-003745d6fff1.png)

**Comment by Rahul-Baba** [comment]
> The dev said this to me
> ![Screenshot_20200903-103840](https://user-images.githubusercontent.com/24226435/92068645-a88d4600-edd1-11ea-91bb-003745d6fff1.png)

Thank for Reply Sir, Which Software Dev are using bro

**Comment by castipo** [comment]
Python

**Comment by Rahul-Baba** [comment]
> Python

Thanks again sir please tell me how many config.json we need to creat

**Comment by south1907** [comment]
Hi, you need create phone.txt format:

+19456734680;1654678;adc6f3c76c2f21676d53be2e9gddt

--> if you have many account, add it to "accounts" array:

"accounts": [
{
"phone": "+19354678903",
"api_id": 1670964,
"api_hash": " 6dhj5e6f3c72c2f21676d53be2ed5gh8jh4"
},
{
"phone": "+18543680074",
"api_id": 1790431,
"api_hash": "ggrl6g3c72c2f21676d53be2eyt69gfd5"
}
]

**Comment by Rahul-Baba** [comment]
> Hi, you need create phone.txt format:
> 
> +19456734680;1654678;adc6f3c76c2f21676d53be2e9gddt
> 
> --> if you have many account, add it to "accounts" array:
> 
> "accounts": [
> {
> "phone": "+19354678903",
> "api_id": 1670964,
> "api_hash": " 6dhj5e6f3c72c2f21676d53be2ed5gh8jh4"
> },
> {
> "phone": "+18543680074",
> "api_id": 1790431,
> "api_hash": "ggrl6g3c72c2f21676d53be2eyt69gfd5"
> }
> ]

Ok thankyou so much for your reply sir i have 20 account and i will try

**Comment by Rahul-Baba** [comment]
After Edit config.json like This

![Screenshot (1)](https://user-images.githubusercontent.com/69967236/92146439-554dde80-ee37-11ea-8d8e-de1c4ec40a41.png)
Get This Error 
![Screenshot (2)](https://user-images.githubusercontent.com/69967236/92146491-6dbdf900-ee37-11ea-84b0-4f463a0f8a3c.png)
Pls anyone tell how to edit config.json

**Comment by Rahul-Baba** [comment]
getdata.py not open or read phone.txt therefore user is not authorized, than print 'dang nhap khong thanh cong' but nobody can solve here this issue 😟
