### ISSUE TITLE
FileNotFoundError [Errno 2] (How to edit config.json) 

### ISSUE THREAD

**Issue by Rahul-Baba** [south1907/addmember-telegram#16]
When I edit config.json like this

![Screenshot (1)](https://user-images.githubusercontent.com/69967236/92146677-aeb60d80-ee37-11ea-8b00-5faa6c7c3647.png)

After that Run run init_session.py
Than get this error
![Screenshot (2)](https://user-images.githubusercontent.com/69967236/92146874-fccb1100-ee37-11ea-853b-0d58c2e9cb2e.png)
Please help how can edit config.json in proper way

**Comment by south1907** [comment]
Hi, you are in folder C:\User\Sannvi

You need `cd` to folder project.

And file config.json seem error format: just one param `accounts` and don't have key `array`

**Comment by Rahul-Baba** [comment]
> Hi, you are in folder C:\User\Sannvi
> 
> You need `cd` to folder project.
> 
> And file config.json seem error format: just one param `accounts` and don't have key `array`

Like this C:\User\Sannvi\cd  or what sir

**Comment by Rahul-Baba** [comment]
When I run init_session.py with this config 
![Screenshot (18)](https://user-images.githubusercontent.com/69967236/92205066-87485a80-eea2-11ea-867b-6d5fbf17b56a.png)
I always get otp and login success
But when I edit config like this
![Screenshot (19)](https://user-images.githubusercontent.com/69967236/92205151-b65ecc00-eea2-11ea-86f4-4fcd6036359c.png)
I get always this error
![Screenshot (20)](https://user-images.githubusercontent.com/69967236/92205193-cd052300-eea2-11ea-8fc5-c65971b46aae.png)
Please sir anyone tell me how to fix this 
Please🙏🙏🙏🙏🙏🙏

**Comment by Rahul-Baba** [comment]
Thanks South 1907

**Comment by Rajaghosh0007** [comment]
> When I edit config.json like this
> 
> ![Screenshot (1)](https://user-images.githubusercontent.com/69967236/92146677-aeb60d80-ee37-11ea-8b00-5faa6c7c3647.png)
> 
> After that Run run init_session.py
> Than get this error
> ![Screenshot (2)](https://user-images.githubusercontent.com/69967236/92146874-fccb1100-ee37-11ea-853b-0d58c2e9cb2e.png)
> Please help how can edit config.json in proper way

please help me to add multiple number in config.json

**Comment by Rajaghosh0007** [comment]
hi Rahul-Baba please help me
