### ISSUE TITLE
how can i find group_target_id and group_source_id ?

### ISSUE THREAD

**Issue by tiagoss88** [south1907/addmember-telegram#18]
Hello, i'd like to know how can i find this id numbers from my telegram group?

group_target_id
group_source_id

thanks

**Comment by castipo** [comment]
run get_data.py , without Proxy, u will get anything u want

**Comment by Rahul-Baba** [comment]
getdata.py not open or read phone.txt therefore user is not authorized, than print 'dang nhap khong thanh cong' but nobody can solve here this issue 😟

**Comment by Rahul-Baba** [comment]
> run get_data.py , without Proxy, u will get anything u want

But get_data.py not creat csv
