### ISSUE TITLE
:telethon.network.mtprotosender:Attempt 1 at connecting failed: TimeoutError: 

### ISSUE THREAD

**Issue by premnathdey** [south1907/addmember-telegram#2]
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 2 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 3 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 4 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Connection error 5 during auth_key gen: ConnectionError: Not connected
WARNING:telethon.network.mtprotosender:Connection error 6 during auth_key gen: ConnectionError: Not connected
Traceback (most recent call last):
  File "getonlygroup.py", line 21, in <module>
    client.connect()
  File "/opt/anaconda3/lib/python3.7/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.7/site-packages/telethon/client/telegrambaseclient.py", line 478, in connect
    proxy=self._proxy
  File "/opt/anaconda3/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 125, in connect
    await self._connect()
  File "/opt/anaconda3/lib/python3.7/site-packages/telethon/network/mtprotosender.py", line 250, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)

**Comment by premnathdey** [comment]
Can You help me why I am getting this error? 
I had used with and without a VPN but both doesn't work for me.

**Comment by south1907** [comment]
Hi, telegram need proxy to connect. 
I guess my proxy I fix in my code in my code is expired.
You can search "mtproxy list free" and choice it yourself.

**Comment by nishankk18** [comment]
Could anyone give a detailed walkthrough on how to do it from the start? would be a great help thank you

**Comment by nishankk18** [comment]
> Hi, telegram need proxy to connect.
> I guess my proxy I fix in my code in my code is expired.
> You can search "mtproxy list free" and choice it yourself.

I #ed the proxy yet unable to run the code without errors. 'client': <telethon.client.telegramclient.TelegramClient object at 0x000001B455CF6F28>}  This is the error i get.

**Comment by premnathdey** [comment]
> Could anyone give a detailed walkthrough on how to do it from the start? would be a great help thank you

https://www.youtube.com/watch?v=Kv0pGqawZPI

Follow this youtube tutorial

**Comment by south1907** [comment]
> > Could anyone give a detailed walkthrough on how to do it from the start? would be a great help thank you
> 
> https://www.youtube.com/watch?v=Kv0pGqawZPI
> 
> Follow this youtube tutorial

Nice =))

**Comment by south1907** [comment]
Simple, you need remove proxy in code. see new file [init_session.py](https://github.com/south1907/addmember-telegram/blob/master/init_session.py#L21)

**Comment by south1907** [comment]
I updated in commit https://github.com/south1907/addmember-telegram/commit/65d25565be31c69fbfa903cbf2cc7ec5ac363a27
