### ISSUE TITLE
How To Fix  line 6, in <module>     with open('config.json', 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

### ISSUE THREAD

**Issue by Duckonice** [south1907/addmember-telegram#21]
**I Edit phone.example.txt And Rename to  phone.txt and  Edit config.example.json And Rename to config.json, I also Rename config.example.json  To config.json.txt and config.txt But always Get This error** 

![Screenshot (1)](https://user-images.githubusercontent.com/71084347/92746792-6cf5fd00-f338-11ea-94ed-def988ce6315.png)

![Screenshot (2)](https://user-images.githubusercontent.com/71084347/92746833-75e6ce80-f338-11ea-8fa3-783eccdf180c.png)
How to Fix This

**Comment by south1907** [comment]
I updated in commit https://github.com/south1907/addmember-telegram/commit/65d25565be31c69fbfa903cbf2cc7ec5ac363a27
