### ISSUE TITLE
getdata. py issue

### ISSUE THREAD

**Issue by Duckonice** [south1907/addmember-telegram#22]
How to fix ' dang nhap khong cong ' if anyone know please tell

**Comment by south1907** [comment]
I updated in commit https://github.com/south1907/addmember-telegram/commit/65d25565be31c69fbfa903cbf2cc7ec5ac363a27

**Comment by south1907** [comment]
I updated in commit https://github.com/south1907/addmember-telegram/commit/65d25565be31c69fbfa903cbf2cc7ec5ac363a27
