### ISSUE TITLE
If you can't help you don't create this type of script

### ISSUE THREAD

**Issue by Duckonice** [south1907/addmember-telegram#24]
Hay South if you can't reply or you can't help, why you creat this type of Script, github not for you if you not solve other devlepoers problem

**Comment by south1907** [comment]
Thank you for your idea.
This is not complete, I will close it and update in the future!

**Comment by Rahul-Baba** [comment]
> Thank you for your idea.
> This is not complete, I will close it and update in the future!

Thanks, 🙏

**Comment by south1907** [comment]
I updated in commit https://github.com/south1907/addmember-telegram/commit/65d25565be31c69fbfa903cbf2cc7ec5ac363a27
