### ISSUE TITLE
Goooood

### ISSUE THREAD

**Issue by Rahul-Baba** [south1907/addmember-telegram#28]
Finally your script is working now thanks but please tell how to convert normal group to super group

**Comment by south1907** [comment]
Please search Google before create issue!
I copy you question: "how to convert normal group to super group telegram" and search Google.
Have many result...

**Comment by Rahul-Baba** [comment]
Ok thaks

**Comment by Rajaghosh0007** [comment]
> Finally your script is working now thanks but please tell how to convert normal group to super group

I am searching this in Google..but this option are not showing in telegram...have you find this????

**Comment by south1907** [comment]
https://www.wikihow.com/Convert-a-Telegram-Group-to-a-Supergroup-on-PC-or-Mac
