### ISSUE TITLE
Weird Users Error (ERROR IN IMAGE )

### ISSUE THREAD

**Issue by nishankk18** [south1907/addmember-telegram#3]
![image](https://user-images.githubusercontent.com/58303791/88373694-edc35e80-cdb5-11ea-8867-609bbf8b3458.png)

**Comment by south1907** [comment]
Please check file `/data/user/' + phone + "_" + str(group_source_id) + '.csv`

run getdata.py to have files

**Comment by nishankk18** [comment]
I already have those data files created. Is there a limit to the number of clients i.e accounts we can run at a time?

**Comment by south1907** [comment]
You need 20 accounts to run, if not, Telegram API will be floor error.

**Comment by nishankk18** [comment]
> You need 20 accounts to run, if not, Telegram API will be floor error.

Doing with 56 Accounts working great <3 THANKS a LOT

**Comment by south1907** [comment]
> > You need 20 accounts to run, if not, Telegram API will be floor error.
> 
> Doing with 56 Accounts working great <3 THANKS a LOT

Greet, I will close issue.
