### ISSUE TITLE
some weird issue

### ISSUE THREAD

**Issue by ashkaaaan** [south1907/addmember-telegram#32]
Hello and thank you for your nice project here

recently I face this issue for all my accounts very soon maybe after 10 user adds:

Error Fooling cmnr
Traceback (most recent call last):
  File "c:\github\add_member.py", line 141, in <module>
    client(InviteToChannelRequest(target_group_entity,[user_to_add]))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.PeerFloodError: Too many requests (caused by InviteToChannelRequest)

and project stops working

the user is not limited yet but this issue happens, what can be the cause?

**Comment by Rahul-Baba** [comment]
You can add only 50 members using one account, if you have 10 account it means you can add 500 members only

**Comment by ashkaaaan** [comment]
but now I made a new account and this problem happened only after 2 member adds

**Comment by ashkaaaan** [comment]
> You can add only 50 members using one account, if you have 10 account it means you can add 500 members only

but now I made a new account and this problem happened only after 2 member adds

**Comment by Rahul-Baba** [comment]
> > You can add only 50 members using one account, if you have 10 account it means you can add 500 members only
> 
> but now I made a new account and this problem happened only after 2 member adds

Use real number, not virtual

**Comment by ashkaaaan** [comment]
> > > You can add only 50 members using one account, if you have 10 account it means you can add 500 members only
> > 
> > 
> > but now I made a new account and this problem happened only after 2 member adds
> 
> Use real number, not virtual

You mean 50 member adds per 24 hours or forever?!

**Comment by Rahul-Baba** [comment]
> > > > You can add only 50 members using one account, if you have 10 account it means you can add 500 members only
> > > 
> > > 
> > > but now I made a new account and this problem happened only after 2 member adds
> > 
> > 
> > Use real number, not virtual
> 
> You mean 50 member adds per 24 hours or forever?!

Yes one number add 50 members per 24 hours

**Comment by Rahul-Baba** [comment]
> Hello and thank you for your nice project here
> 
> recently I face this issue for all my accounts very soon maybe after 10 user adds:
> 
> Error Fooling cmnr
> Traceback (most recent call last):
> File "c:\github\add_member.py", line 141, in
> client(InviteToChannelRequest(target_group_entity,[user_to_add]))
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sync.py", line 39, in syncified
> return loop.run_until_complete(coro)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
> return future.result()
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 30, in **call**
> return await self._call(self._sender, request, ordered=ordered)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 77, in _call
> result = await future
> telethon.errors.rpcerrorlist.PeerFloodError: Too many requests (caused by InviteToChannelRequest)
> 
> and project stops working
> 
> the user is not limited yet but this issue happens, what can be the cause?

You are right bro today I try this script with 30 numbers but this tool add only 30 members 😒😒😒😒😒
