### ISSUE TITLE
how to find group id

### ISSUE THREAD

**Issue by farshad666farshad** [south1907/addmember-telegram#4]
hi i have problem with group id how i can find group id source and target i use old version of telegram ad member in that one just should join to group no need group chat id can u help me and tnx for kindly reply 
and i have question also in old versions i cant ad user without user name i mean if member dont have username cant ad to group in this platform also same?

**Comment by south1907** [comment]
Hi, you need to run getdata.py and then see file in folder data/group.
And map with name group you want
