### ISSUE TITLE
Add successful but..

### ISSUE THREAD

**Issue by TUXGroup** [south1907/addmember-telegram#40]
Hello,
After adding members to group, telegram service show ... added ... , but after a while some users left group automatically.It seems there is a limit for adding on telegram but how can solve it?

**Comment by south1907** [comment]
What happen after some users left group?
Service is run normally? Speed ? or Throw the error?

**Comment by ByeCoder** [comment]
Everything going to normal
I figure out that after 3 times that users added to group and the count of group doesn't going up then every trying has normal service notification and update of add but the users will not be participant of group
If I set upper than 30 second for each trying it will decrease this issue but this is a big number

**Comment by ByeCoder** [comment]
No error after adding till it reaches to PEER FLOOD 
Speed is about 1-6 seconds for each adding 
After each trying I get receiving add member service
But no such member for chat

**Comment by DanielTheGeek** [comment]
This has been fixed in #51
