### ISSUE TITLE
DOCS: Best practices

### ISSUE THREAD

**Issue by felinto-dev** [south1907/addmember-telegram#47]
1. The number of 20 Telegram accounts to invite members is a recommendation, correct? Can I add more or less accounts if I want?
2. Is there any recommendation on the minimum number of accounts that should be used depending on the size of the group? If the group has 1000 members for example, what is the minimum number of accounts you recommend to invite members?
3. If during the bulk add member process, all telegram accounts are suspended by flood error, is it safe to run the same script all the time and will it keep adding from the last known user?

**Comment by nimma0001** [comment]
1. No u can use 1 or 100 depend on how many account u have.
2. 40 is good amount to run [i use 8-10](daily invite 300-500)
3. Yes script will add from last known user. But it slnot safe as more limitation u get from telegram the higher chance of account ban. Dont use group owner account

**Comment by south1907** [comment]
Hi, I will create Q&A for frequency question
[Q&A](https://github.com/south1907/addmember-telegram/wiki/3.-Q&A)

**Comment by south1907** [comment]
Closed
