### ISSUE TITLE
It works, but I need help

### ISSUE THREAD

**Issue by hofnar05** [south1907/addmember-telegram#48]
In what part of the script do I need to change to numbers to make it sleep longer?

I want it to start with for example 120 seconds instead of 3.3 seconds and than adding up..
I have run it for a few times now and I notice that if it use the client with 120 second that it will stay up longer.

I have in total over 40 clients running.

Thanks for all the effort!
I love your project <3

**Comment by felinto-dev** [comment]
"I have run it for a few times now and I notice that if it use the client with 120 second that it will stay up longer."

How did you notice that if you don't know how to change the delay from 3.3 seconds to 120 seconds?

120 / 40 = 3

I guess you are looking for it:
https://github.com/south1907/addmember-telegram/blob/master/add_member.py#L152

**Comment by felinto-dev** [comment]
"I have run it for a few times now and I notice that if it use the client with 120 second that it will stay up longer."

How did you notice that if you don't know how to change the delay from 3.3 seconds to 120 seconds?

120 / 40 = 3

I guess you are looking for it:
https://github.com/south1907/addmember-telegram/blob/master/add_member.py#L152

**Comment by DanielTheGeek** [comment]
https://t.me/amtcommunity

Join the Telegram community for faster support.
