### ISSUE TITLE
Code rapidly finish's all acounts without skipping to next account

### ISSUE THREAD

**Issue by yarinhalili** [south1907/addmember-telegram#50]
Code rapidly finish's all acounts without skipping to next account and i got after each try an "error other" messeage,
All I need to do is to remove the number which the code  got stuck on and wait time, but after it does it  ,the current_count reaches to maximum and there is no way to remeber where the program stopped

**Comment by yarinhalili** [comment]
Happens from time to time

**Comment by magdals994silvi94** [comment]
tengo el mismo problema, lo utilizo uno por uno y tengo que borrar de donde se quedo los miembros porque empieza desde el inicio cuando el bot se detiende

**Comment by DanielTheGeek** [comment]
This happens when you’re trying to add more than 200 people to a channel. There’s a limit set by Telegram when adding people programmatically.

**Comment by yarinhalili** [comment]
> This happens when you’re trying to add more than 200 people to a channel. There’s a limit set by Telegram when adding people programmatically.

So after 200 users sim gets blocked for ever?
