### ISSUE TITLE
Addind the same user for no reason

### ISSUE THREAD

**Issue by felinto-dev** [south1907/addmember-telegram#57]
![image](https://user-images.githubusercontent.com/32253743/184792087-24466b6c-7166-49f8-9cd2-cc6e7ffb0fad.png)

I don't know what happens. That's weird. I need to kill the script because CRTL + C does not works.

**Comment by south1907** [comment]
If you use linux system, please use
`kill -9 pid`

**Comment by south1907** [comment]
Closed
