### ISSUE TITLE
can any one help me

### ISSUE THREAD

**Issue by abhisak74** [south1907/addmember-telegram#6]
[
![Capture](https://user-images.githubusercontent.com/69030358/90949903-9ffc4d80-e46a-11ea-8324-42a058bed74b.PNG)
](url)

**Comment by south1907** [comment]
are you change your phone number in file config.json

**Comment by abhisak74** [comment]
How should i change bro

**Comment by Rahul-Baba** [comment]
getdata.py not open or read phone.txt therefore user is not authorized, than print 'dang nhap khong thanh cong' but nobody can solve here this issue 😟
