### ISSUE TITLE
There has been no problem so far. There was a problem after adding the account.

### ISSUE THREAD

**Issue by mintolkim** [south1907/addmember-telegram#66]
Traceback (most recent call last):
  File "c:\set up\addmember-telegram-master\add_member.py", line 207, in <module>
    user = current_client['users'][i]
IndexError: list index out of range
PS C:\set up\addmember-telegram-master>

Pleas help me

**Comment by south1907** [comment]
Are you run init_session.py

**Comment by south1907** [comment]
Please check new update
