### ISSUE TITLE
Error on line no 105 in addmember.py file.

### ISSUE THREAD

**Issue by Dhruvkanani** [south1907/addmember-telegram#7]
I already followed all your steps perfectly. I logged in to accounts but then addmember.py gives error on line no 105 showing array index 'users'. Sir please solve this problem. Thank You 😊

**Comment by south1907** [comment]
are you run getdata.py ?
because don't have file user/... which user group you want to add

**Comment by Rahul-Baba** [comment]
> are you run getdata.py ?
> because don't have file user/... which user group you want to add

Not working
