### ISSUE TITLE
Cant add member to targer group

### ISSUE THREAD

**Issue by IbrahimSerhat** [south1907/addmember-telegram#75]
Hi dear,

When I use old version, everything works as well but, after When I updated to one api more accounts system, It looks adding member as successfully but no effected.

I checked target group user name and source member group user name too many times but I cant find any fail

**Comment by south1907** [comment]
Have any logs is printed on your screen?

**Comment by IbrahimSerhat** [comment]
![image](https://user-images.githubusercontent.com/9952100/205112491-a7ce0f8c-eac1-4f27-973d-cf384a1a4149.png)

**Comment by south1907** [comment]
Please pull new code
I have recently update logic: check member exists in target group, if it exists, not re-add to target:
You can see code in commit: https://github.com/south1907/addmember-telegram/commit/28553a42a0a84f2fcc8df686cac0646f19cbe441

**Comment by IbrahimSerhat** [comment]
> Please pull new code I have recently update logic: check member exists in target group, if it exists, not re-add to target: You can see code in commit: [28553a4](https://github.com/south1907/addmember-telegram/commit/28553a42a0a84f2fcc8df686cac0646f19cbe441)

thank you it solved it. It was not add member to target group because of member already added.

**Comment by south1907** [comment]
Yep, but It is not complete.
Some members have processed because some member while added is error (Error Privacy).
And when re-run, it will re-add. It is bad.
I will Trace log added and check Privacy while add.
Please follow it: https://github.com/users/south1907/projects/2/views/1

**Comment by south1907** [comment]
Done in https://github.com/south1907/addmember-telegram/commit/09f8c2170cf707fc1db60347c3ac8e21173f4b0c

**Comment by IbrahimSerhat** [comment]
It works as very well. I am very satisfied thank you
