### ISSUE TITLE
PeerFloodError

### ISSUE THREAD

**Issue by mosisedi420** [south1907/addmember-telegram#77]
hi...im create account telegram....account safe and no problem......i using bot for add member to group......but error:
telethon.errors.rpcerrorlist.PeerFloodError: Too many requests (caused by InviteToChannelRequest)

![499c4fba-df1a-44c9-b002-32623a984008 copy](https://user-images.githubusercontent.com/83016119/206172221-e4caf5dd-85ce-4a20-b354-7ecde38463de.jpg)

**Comment by mosisedi420** [comment]
My account is not blocked, but error FloodWaitError, in Terminal like as:
FloodWaitError

i waited 77464 seconds

**Comment by south1907** [comment]
oh, it is normal.
Your account is not block, but it is FloodWaitError, you need wait many seconds as it notice

**Comment by mosisedi420** [comment]
thanks....a waiting 3day...........but not fiexd.......

**Comment by south1907** [comment]
And have FloodWaitError when you re-run?

**Comment by mosisedi420** [comment]
yes

**Comment by mosisedi420** [comment]
total is 3 members

**Comment by south1907** [comment]
And your problems is solved?

**Comment by mosisedi420** [comment]
yes

**Comment by south1907** [comment]
And I will close it :))
