### ISSUE TITLE
Error After Remove Proxy 

### ISSUE THREAD

**Issue by Rahul-Baba** [south1907/addmember-telegram#8]
Hi sir You say Remove proxy, but after remove proxy getdata.py error dang nhap khong thanh cong please tell how to fix this

**Comment by castipo** [comment]
u need just remove until like this only 

		client = TelegramClient(phone, api_id, api_hash)

**Comment by Rahul-Baba** [comment]
> u need just remove until like this only
> 
> ```
> 	client = TelegramClient(phone, api_id, api_hash)
> ```

Already Remove but dang nhap khong thanh cong after Remove

**Comment by south1907** [comment]
I updated in commit https://github.com/south1907/addmember-telegram/commit/65d25565be31c69fbfa903cbf2cc7ec5ac363a27
