### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by DobrOvKedaX** [south1907/addmember-telegram#80]
This script works no more

**Comment by south1907** [comment]
Can you show me what is your problems?

**Comment by DobrOvKedaX** [comment]
The script shows the successful addition of participants to the chat, but only 1 person is added from each account.
The chat receives notifications about adding participants, but when checking their profiles, they are not subscribed to the chat.
The photo shows a lot of messages about adding, but the number of subscribers has not grown. I checked everyone. On the same scripts from other developers, users report the same problem.



![Снимок экрана_20230131_131205](https://user-images.githubusercontent.com/25393411/216965320-efd05aa4-0759-4a1f-bdb0-60f0bed09a4a.png)

**Comment by DobrOvKedaX** [comment]
![Снимок экрана 2023-01-31 132714](https://user-images.githubusercontent.com/25393411/216965479-bad19367-2272-40b3-bfd9-a9e77835a18f.png)

**Comment by DanielTheGeek** [comment]
We will look into this internally and give you feedback.

**Comment by FlyCodex** [comment]
I am also having an issue with this script. I have opened an issue separately explaining my issues

**Comment by south1907** [comment]
Please follow this: https://github.com/users/south1907/projects/2/views/1?pane=issue&itemId=19896414
we will check it

**Comment by south1907** [comment]
Still working normal, please send me your source group and target group

**Comment by FlyCodex** [comment]
send me your telegram user or ID so we can chat

**Comment by devDarom** [comment]
As i see, it works only id u do login->GET DATA> ADD
By this order
