### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by FlyCodex** [south1907/addmember-telegram#81]
**Describe the bug**
python add_member.py <> following issue comes up: This account with {my number} is not in target group. list index out of range. 

- I am in the group, I made a test group also. Both have the same error! Could you look into this issue please :)

**Comment by south1907** [comment]
Please follow this: https://github.com/users/south1907/projects/2/views/1?pane=issue&itemId=19896414
we will check it

**Comment by FlyCodex** [comment]
Do I need to do anything? I cant see my issue up there yet

**Comment by FlyCodex** [comment]
Hi its been some time and nothings happened ?

**Comment by VasilMirov** [comment]
@FlyCodex yeah i don't think they are up for solving it...

**Comment by south1907** [comment]
Sorry, in my case, I still add normally
