### ISSUE TITLE
Member is shown as invited in group but group number isn't changed

### ISSUE THREAD

**Issue by VasilMirov** [south1907/addmember-telegram#82]
**Describe the bug**
There is a problem with the functionality. I'm running the script, it scrapes the members of a public group. I then run the add_member file and users are added to my group as expected. In my group, it's shown as "ClientName invited ScrapedMember" but the group's number doesn't rise (meaning that the total number of members in the group doesn't change). Which is very weird, and I can't explain why. Have you encountered this as well? 
I would like to mention that the group I'm adding members to (my group) is 1100 members.

**Comment by south1907** [comment]
Please follow this: https://github.com/users/south1907/projects/2/views/1?pane=issue&itemId=19896414
we will check it

**Comment by VasilMirov** [comment]
Mhm okej, nice guys. Hope this gets solved. Keep up the good work!

**Comment by VasilMirov** [comment]
I will also add that, one week ago this problem was not present. I created my group and got up to 1k members pretty fast. But 4 days ago that all changed. Could a telegram update change all of this?

**Comment by VasilMirov** [comment]
@south1907 is there any update on the situation?

**Comment by alekla** [comment]
hi @south1907, is any updates?

**Comment by VasilMirov** [comment]
@south1907 no the problem is still there
