### ISSUE TITLE
telethon error

### ISSUE THREAD

**Issue by myketysonpot** [south1907/addmember-telegram#85]
**Describe the bug**
when running get_members.py i get this error: telethon.errors.rpcerrorlist.ChatAdminRequiredError: Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)
Segmentation fault (core dumped)

Thank You for your work!

**Screenshots**

**Comment by south1907** [comment]
It seem you accounts is not permission to add member to that group.
You try to add member manual by that accounts
