### ISSUE TITLE
Chatadminrequirederror

### ISSUE THREAD

**Issue by bsde1234** [south1907/addmember-telegram#92]
get member give error
![IMG_20231217_125219_169](https://github.com/south1907/addmember-telegram/assets/35421561/d8b020cf-7f9d-40b4-945d-059aacb09916)

**Comment by south1907** [comment]
your account run need to be acccess the source group

**Comment by bsde1234** [comment]
I am at source group as member and destination group as admin

**Comment by south1907** [comment]
In get member of channel, you must be a admin
